name: taskfy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.3.4
  flutter_riverpod: ^2.3.6
  go_router: ^14.8.0
  file_picker: ^8.3.5
  fl_chart: ^0.55.2
  shared_preferences: ^2.5.2
  google_fonts: ^6.2.1
  logging: ^1.3.0
  path: ^1.9.0
  mime: ^2.0.0
  get_it: ^7.6.7
  http: ^1.3.0
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - lib/l10n/
